### 张量的保存和加载

In [1]:
import torch

In [2]:
a = torch.rand(6)
a

tensor([0.7962, 0.3250, 0.4597, 0.0873, 0.7479, 0.6129])

In [4]:
import os 
os.makedirs("model", exist_ok = True)
torch.save(a,"model/tensor_a")

In [5]:
torch.load("model/tensor_a")

C:\Users\Ye Guiren\AppData\Local\Temp\ipykernel_16356\18023226.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load("model/tensor_a")


tensor([0.7962, 0.3250, 0.4597, 0.0873, 0.7479, 0.6129])

In [6]:
a = torch.rand(6)
b = torch.rand(6)
c = torch.rand(6)
[a,b,c]

[tensor([0.4978, 0.9532, 0.5346, 0.8579, 0.9015, 0.4092]),
 tensor([0.0424, 0.9027, 0.6611, 0.1578, 0.1167, 0.6473]),
 tensor([0.1675, 0.2779, 0.4797, 0.5089, 0.9714, 0.3154])]

In [7]:
torch.save([a,b,c],"model/tensor_abc")

In [8]:
torch.load("model/tensor_abc")

C:\Users\Ye Guiren\AppData\Local\Temp\ipykernel_16356\3520973659.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load("model/tensor_abc")


[tensor([0.4978, 0.9532, 0.5346, 0.8579, 0.9015, 0.4092]),
 tensor([0.0424, 0.9027, 0.6611, 0.1578, 0.1167, 0.6473]),
 tensor([0.1675, 0.2779, 0.4797, 0.5089, 0.9714, 0.3154])]

In [10]:
tensor_dict = {'a':a,'b':b,'c':c}
tensor_dict

{'a': tensor([0.4978, 0.9532, 0.5346, 0.8579, 0.9015, 0.4092]),
 'b': tensor([0.0424, 0.9027, 0.6611, 0.1578, 0.1167, 0.6473]),
 'c': tensor([0.1675, 0.2779, 0.4797, 0.5089, 0.9714, 0.3154])}

In [11]:
torch.save(tensor_dict,"model/tensor_dict_abc")

In [12]:
torch.load("model/tensor_dict_abc")

C:\Users\Ye Guiren\AppData\Local\Temp\ipykernel_16356\3326522502.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load("model/tensor_dict_abc")


{'a': tensor([0.4978, 0.9532, 0.5346, 0.8579, 0.9015, 0.4092]),
 'b': tensor([0.0424, 0.9027, 0.6611, 0.1578, 0.1167, 0.6473]),
 'c': tensor([0.1675, 0.2779, 0.4797, 0.5089, 0.9714, 0.3154])}

### 模型的读写

In [14]:
from torch import nn
class MLP(nn.Module):
# 定义MLP类,继承自nn.Module,使MLP具备神经网络的基本功能
# nn.Module:Pytorch中所有神经网络模型的基类
    def __init__(self, input_size,hidden_size,num_classes):
        # input_size:输入数据的维度
        # hidden_size：隐藏层的神经元数量
        # num_classes:输出分类的数量
        super(MLP,self).__init__()
        # 调用父类初始化方法
        self.fc1 = nn.Linear(input_size,hidden_size)
        # 第一个全连接层，输入维度 -> 隐藏层维度
        self.relu = nn.ReLU()
        # 定义ReLu激活函数，引入非线性
        self.fc2 = nn.Linear(hidden_size,hidden_size)
        # 第二个全连接层，隐藏层 -> 隐藏层
        self.fc3 = nn.Linear(hidden_size, num_classes)
        # 第三个全连接层，隐藏层 -> 输出类别数
# nn.Linear:定义全连接层，参数为输入维度和输出维度
# super(MLP, self).__init__():必修调用父类初始化，确保模型正确继承nn.Module的功能
    def forward(self,x):
        out = self.fc1(x)
        # 第一层运算
        out = self.relu(out)
        # 对第一层的输出应用ReLU激活函数
        out = self.fc2(out)
        # 激活后的结果传入第二层全连接层
        out = self.relu(out)
        # 对第二层输出再次应用ReLU激活
        out = self.fc3(out)
        # 最后传入第三层全连接层，输出结果用于分类
        return out
input_size = 28*28
hidden_size = 512
# 隐藏层神经元数量为512,用于特征提取和特征转换
num_classes = 10
model = MLP(input_size, hidden_size, num_classes)

### 方法1

In [17]:
# 保存模型参数
torch.save(model.state_dict(),"model/mlp_state_dict.pth")
# model.state_dict()：获取模型model的参数字典，包含各层的权重、偏置等参数

In [18]:
mlp_state_dict = torch.load("model/mlp_state_dict.pth")
# 加载保存的参数字典
model_load = MLP(input_size,hidden_size,num_classes)
# 重新实例化与原模型结构相同的MLP模型model_load，确保层结构、参数数量一致，才能正确加载参数
model_load.load_state_dict(mlp_state_dict)
# 将加载的参数字典mlp_state_dict应用导新模型model_load

C:\Users\Ye Guiren\AppData\Local\Temp\ipykernel_16356\342098640.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  mlp_state_dict = torch.load("model/mlp_state_dict.pth")


<All keys matched successfully>

### 方法2

In [19]:
torch.save(model,"model/mlp_model.pth")
# 保存则会个那个模型（含结构与参数），文件较大

In [20]:
mlp_load = torch.load("model/mlp_model.pth")
# 直接加载完整模型，无需重新定义模型结构

C:\Users\Ye Guiren\AppData\Local\Temp\ipykernel_16356\234023158.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  mlp_load = torch.load("model/mlp_model.pth")


### 方式3：checkpoint

In [21]:
torch.save({
    'epoch':epoch,
    'model_state_dict':model.state_dict(),
    'optimizer_state_dict':optimizer.state_dict(),
    'loss':loss,
    },model/mlp_model_checkpoint.pth)

NameError: name 'epoch' is not defined

In [ ]:
model = TheModelClass(*args, **kwargs)
# 按原定义实例化模型  
optimizer = TheOptimizerClass(*args, **kwargs)
# 按原定义实例化优化器  

checkpoint = torch.load(PATH)
# 加载检查点数据  
model.load_state_dict(checkpoint['model_state_dict'])
# 恢复模型参数  
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
# 恢复优化器状态  
epoch = checkpoint['epoch']
# 恢复训练轮次记录  
loss = checkpoint['loss']
# 恢复保存时的损失值  
model.eval()
# 将模型设为评估模式（如需继续训练，可调整为训练模式）  